import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Young_Serif} from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });
const young = Young_Serif({
  subsets: ["latin"],
  weight: "400",
  variable: '--font-young'
});

export const metadata: Metadata = {
  title: "Pixel Of Manoj",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
